# This workflow builds and tests the package to sanity check the code.

name: Main

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
      with:
        swift-version: "5.5.2"
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
