# This workflow builds and tests the package to sanity check the code.

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
